### ISSUE TITLE
When creating new user, I receive an HTTP Basic Auth Prompt

### ISSUE THREAD

**Issue by tiagofassoni** [garrettqmartin8/volition#20]
Hello.

First of all, thanks for the project. I saw on /r/selfhosted, spawned a Heroku, but it asks for an HTTP Basic Auth on creating a new user. Any ideas?

**Comment by garrettqmartin8** [comment]
Hi @tiagofassoni. Thanks for giving Volition a try!

I just pushed a [fix](https://github.com/garrettqmartin8/volition/commit/ffc898902e61c47ecd25fcaa2fcadc3f5010624c) for this issue to master. I wasn't checking whether or not the instance was self-hosted or not before setting the http basic auth prompt.

If you run clone the repo from your Heroku instance and run `bin/update_heroku`, your app should get the update and it'll be good to go!

**Comment by garrettqmartin8** [comment]
@tiagofassoni closing this for now. If you're still having issues, go ahead and reopen this issue.

**Comment by tiagofassoni** [comment]
Okay, thanks!
