### ISSUE TITLE
Self-hosting without Heroku?

### ISSUE THREAD

**Issue by JokerQyou** [garrettqmartin8/volition#38]
Could we have self-hosting guide on a standard Linux server?

**Comment by garrettqmartin8** [comment]
Absolutely. I'll work on that soon.

**Comment by jamesacampbell** [comment]
I am trying to do this myself right now. I will add instructions if / when I get it working. Thanks

**Comment by jamesacampbell** [comment]
I got it working on Ubuntu 14.04 and using NGINX to reverse proxy 127.0.0.1:3000 to my public cname on my website. Here is very short guide:

1. Make sure you have postgres installed.
2. Make sure you have ruby 2.4.0 installed.
3. Set username and password as necessary in database.yml in the config folder after git clone.

3. Run the following commands:   
`git clone git@github.com:garrettqmartin8/volition.git`
`cd volition`
`./bin/setup` the gotcha here for me was the `rails db:setup` step. I had to change my postgres config to trust default localhost, had to install rvm, and had to bundle config
4. Run `rails s`

**Comment by garrettqmartin8** [comment]
@jamesacampbell fantastic! A pull request to the readme would be much appreciated.

**Comment by jamesacampbell** [comment]
Great @garrettqmartin8 I will work on that this evening as time allows.

**Comment by jamesacampbell** [comment]
pull request submitted to add instructions #46

**Comment by JokerQyou** [comment]
Thanks @jamesacampbell . I'll try it this evening (GMT+8).
