### ISSUE TITLE
Sign in with google is broken

### ISSUE THREAD

**Issue by rohitpaulk** [garrettqmartin8/volition#41]
- Visit https://usevolition.com/users/new
- Click on 'Sign in with Google'

![screen shot 2017-08-23 at 10 00 17 pm](https://user-images.githubusercontent.com/3893573/29627079-7c424c6c-884e-11e7-8e8e-b39b55b3f6e0.png)

**Comment by garrettqmartin8** [comment]
Ah, the reason for this is that Google sign in is only mapped to `www.usevolition.com` and not `usevolition.com`. I'll go make sure both urls are supported.

**Comment by garrettqmartin8** [comment]
It should be working now. Thanks for pointing this out @rohitpaulk
