### ISSUE TITLE
Payment page broken? 

### ISSUE THREAD

**Issue by rohitpaulk** [garrettqmartin8/volition#42]
I tried to add a credit card, and hit the generic Rails error page ("We're sorry, but something went wrong")

The URL was `usevolition.com/users/:my_id`

**Comment by garrettqmartin8** [comment]
@rohitpaulk is this still happening for you? Do you have any other specific steps to reproduce this?

**Comment by rohitpaulk** [comment]
I'll try again and let you know soon

**Comment by garrettqmartin8** [comment]
Fixed in #50
