### ISSUE TITLE
remove stripe integration for self-hosting

### ISSUE THREAD

**Issue by jamesacampbell** [garrettqmartin8/volition#45]
On user sign-up, it redirects to try to do a stripe call and cannot do it. If you go to the login page, the new user can login, so the functionality is not broken, but it would be nice to have a `no_stripe=true` in the config file to completely turn this off. The user settings page is also broken due to stripe. The default license / access should be perpetual or forever if necessary to keep the current paradigm in place without refactoring too much code.

**Comment by garrettqmartin8** [comment]
@jamesacampbell thanks for pointing this out. I totally agree. I'll work on making sure integrations with third parties are more flexible this weekend.

**Comment by garrettqmartin8** [comment]
@jamesacampbell Fixed in #50.

**Comment by jamesacampbell** [comment]
@garrettqmartin8 awesome
